# ============================================================
# 左右后域配置
# ============================================================
[LR_REAR]
input_excel = C:/Users/高登兰/Downloads/TC_用例未涉及部分关键字 (1).xlsx

output_dir = C:/Users/高登兰/Desktop/所有完整代码2026_3_10_重构版/python/release_02_1/out

case_levels = S,A,B,C
case_platforms = MQB
case_models = MQB
case_target_versions = CEA2.x_IPDT2.0,CEA2.x_A_Sample,CEA2.x_B1_Sample

# 勾选的工作表
selected_sheets = TC_用例未涉及部分关键字 (1).xlsx|HIL,TC_用例未涉及部分关键字 (1).xlsx|EM_设备,TC_用例未涉及部分关键字 (1).xlsx|EM_LIN,TC_用例未涉及部分关键字 (1).xlsx|EM_CAN,TC_用例未涉及部分关键字 (1).xlsx|WpsReserved_CellImgList

log_level_min = info

[IOMAPPING]

[DID_CONFIG]
output_dir = C:/Users/高登兰/Desktop/python开发合肥/left-right
output_filename = DIDConfig.txt

[CONFIG_ENUM]

# ============================================================
# 中央域配置
# ============================================================
[CENTRAL]
input_excel = C:/Users/高登兰/Desktop/python开发合肥/python工具转译校验_V1.0.xlsx
selected_sheets = python工具转译校验_V1.0.xlsx|TC

output_dir = C:/Users/高登兰/Desktop/所有完整代码2026_3_10_重构版/python/release_02_1/out

case_levels = S,A,B,C
case_platforms = MQB
case_models = MQB
case_target_versions = CEA2.x_VP1.1(IPDT1.0),CEA2.x_IPDT2.0,CEA2.x_IPDT3.0,CEA2.x_IPDT4.0,CEA2.x_A_Sample,CEA2.x_B1_Sample
log_level_min = info
uds_ecu_qualifier = RDCU

# 运行账号（生成至 output_dir/Configuration/login.txt）
login_username = 
login_password = 

[IgnitionCycle]
waitTime = 
current = 

# ============================================================
# DTC配置
# ============================================================
[DTC]
input_excel = C:/Users/高登兰/Desktop/python开发合肥/python工具转译校验_V1.0.xlsx
selected_sheets = python工具转译校验_V1.0.xlsx|TC

output_dir = C:/Users/高登兰/Desktop/python开发合肥/left-right

case_levels = S,A,B,C
case_platforms = MQB
case_models = MQB
case_target_versions = CEA2.x_VP1.1(IPDT1.0),CEA2.x_IPDT2.0,CEA2.x_IPDT3.0,CEA2.x_IPDT4.0,CEA2.x_A_Sample,CEA2.x_B1_Sample
log_level_min = info
didinfo_inputs = C:/Users/高登兰/Desktop/python开发合肥/LDCU/Reat_Did/reset_did_configure_ldcu.xlsx | *
cin_input_excel = C:/Users/高登兰/Desktop/python开发合肥/LDCU/Hil_clib/MQB/VEEA_LDCU_Clib_GZ_MQB_0127 (1).xlsx
uds_ecu_qualifier = RDCU

[DTC_IOMAPPING]
inputs = C:/Users/高登兰/Desktop/python开发合肥/LDCU/IO_Mapping/CARIAD MQB LDCU-RDCU HiL_IO_mapping0209 (1).xlsx | LZCU1.0

[DTC_CONFIG_ENUM]
inputs = C:/Users/高登兰/Desktop/python开发合肥/LDCU/Set_config/LDCU_Configuration(1).xlsx | *
